apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-cluster
  namespace: sylvain
  labels:
    app: portal-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-cluster
  template:
    metadata:
      labels:
        app: portal-cluster
    spec:
      containers:
      - name: portal-cluster
        image: sylvainpierrot/portal-cluster:v2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi