apiVersion: v1
kind: Service
metadata:
  name: portal-cluster
  namespace: sylvain
spec:
  selector:
    app: portal-cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http