{{ range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
    
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        resources: {{ toYaml $.Values.resources | nindent 10 }}
        image: "{{ .image.repository }}:{{ .image.tag | print }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .containerPort }}
          protocol: TCP
        {{- if .env }}
        env: {{ toYaml .env | nindent 8 }}
        {{- end }}
...
{{ end }}
